# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\",\n\x08Position\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"%\n\x0fJoinGameRequest\x12\x12\n\nplayerName\x18\x01 \x01(\t\"J\n\x10JoinGameResponse\x12\x10\n\x08playerId\x18\x01 \x01(\t\x12$\n\x0cotherPlayers\x18\x02 \x03(\x0b\x32\x0e.game.Position2\xb4\x01\n\x0bGameService\x12;\n\x08JoinGame\x12\x15.game.JoinGameRequest\x1a\x16.game.JoinGameResponse\"\x00\x12\x32\n\x0eUpdatePosition\x12\x0e.game.Position\x1a\x0e.game.Position\"\x00\x12\x34\n\x0cGetPositions\x12\x0e.game.Position\x1a\x0e.game.Position\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSITION']._serialized_start=20
  _globals['_POSITION']._serialized_end=64
  _globals['_JOINGAMEREQUEST']._serialized_start=66
  _globals['_JOINGAMEREQUEST']._serialized_end=103
  _globals['_JOINGAMERESPONSE']._serialized_start=105
  _globals['_JOINGAMERESPONSE']._serialized_end=179
  _globals['_GAMESERVICE']._serialized_start=182
  _globals['_GAMESERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
